* Preliminaries
This is my attempt at creating a non-specialist friendly introduction to the world of Emacs and Org-Mode. This document will continue to be modified.
The latest version of this document was created on <2016-09-01 Thu>
* Welcome to Emacs!
** Introduction
Hello there! This is my attempt to introduce the Emacs text editor to an average biologist, or more generally, any person who is not comfortable writing code, using the terminal (what's that??) or installing packages using a command line. I hope you can see the utility of Emacs over other methods of recording data, jotting down notes from papers that you might be reading, or even creating a document with multiple literature references in it. 

Read on is you are interested in learning about the coolest way to record and share science!
** Why Emacs?
This is the big question: Why EMACS? What is it that makes this text editor(which looks uglier than Notepad!) better than, say, Microsoft Word?
At first glance, the easiest answer to that question is that Emacs is a lot less /distracting/ than Word. It is all plain text! This should already be a huge impetus to switch over; it is the /aesthetic/.
But going beyond looks, Emacs is an immensely versatile piece of software. Describing all its features is quite impossible for me, because, honestly, I don't even know what I don't know about Emacs. It is sufficient to know that /Emacs/ stand for *Editor MACros*, and was originally developed as a set of /macros/ or computer routines to automate text editor functions.

In a nutshell, *Emacs is built to be the most efficient text editor there is*. (Some might argue that it is VI or Nano. To these people I say, do not insult St. IGnucius.) 
** Some Emacs Basics
* Org: Organize your life in plain text
** Some cool things that you can do with Org
* Org-ref: The answer to recording literature searches 
