#+TITLE: Note on maintenance of lab records

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/styles.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./css/github-light.css"/>
#+HTML_HEAD: <script src="./js/scale.fix.js"></script>
#+INFOJS_OPT: view:info 

A major challenge I faced during my rotation with the Hauf Lab was maintaining an electronic lab notebook. 

The advantages of maintaining a paper Lab Notebook are many, including the fact that you can scribble notes and observations at will, it is easy to carry around, and remains a physical record of the mistakes and corrections that you make. On the other hand, the advantages of an electronic labnotebook seem, now, to outweigh those of a traditional paper record. It took me a while to get used to typing out observations and comments during the experiment instead of writing them down, but the fact is that it isn't hard at all. I have experimented with OO and have created a lab notebook template including features for making ToDo lists and comments/observations sections not directly pertinent to the experiment. You can find it [[file:AJ_NB_Template.ott][here]]. However, I have also come across the amazing power and magnificent beauty of LaTex (again!), and have tried using [[http://www.latextemplates.com/template/daily-laboratory-book][this package]], which seems perfect for my needs.

*Update on 160201*
- Ever since I joined Dr. Murali's lab in spring 2016, my entire outlook towards documentation and file organization has changed. Enter =emacs24= and its amazing, all-powerful =org-mode=!!!!
- A nice way of keeping track of the papers I read is turning out to be cite-u-like which is used by Murali and his group.
- [[file:Intro-To-Org.html][Here]] is a document, along with the [[file:Intro-To-Org.org][org-mode file]] that I am creating that I hope will make Emacs an attractive text editor for non-coders well.
